<?
$arUrlRewrite = array(
	array(
		"CONDITION"	=>	"#^/eng/about/news/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"/eng/about/news/index.php",
	),
	array(
		"CONDITION"	=>	"#^/hun/about/news/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"/hun/about/news/index.php",
	),
	array(
		"CONDITION"	=>	"#^/cze/about/news/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"/cze/about/news/index.php",
	),
	array(
		"CONDITION"	=>	"#^/rus/about/news/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"/rus/about/news/index.php",
	),
	array(
		"CONDITION"	=>	"#^/bgr/about/news/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"/bgr/about/news/index.php",
	),
	array(
		"CONDITION"	=>	"#^/hrv/about/news/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"/hrv/about/news/index.php",
	),
	array(
		"CONDITION"	=>	"#^/eng/contracts/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"/eng/contracts/index.php",
	),
	array(
		"CONDITION"	=>	"#^/cze/contracts/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"/cze/contracts/index.php",
	),
	array(
		"CONDITION"	=>	"#^/rus/contracts/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"/rus/contracts/index.php",
	),
	array(
		"CONDITION"	=>	"#^/bgr/contracts/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"/bgr/contracts/index.php",
	),
	array(
		"CONDITION"	=>	"#^/hrv/contracts/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"/hrv/contracts/index.php",
	),
	array(
		"CONDITION"	=>	"#^/hun/contracts/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"/hun/contracts/index.php",
	),
	array(
		"CONDITION"	=>	"#^/bgr/products/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"/bgr/products/index.php",
	),
	array(
		"CONDITION"	=>	"#^/rus/products/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"/rus/products/index.php",
	),
	array(
		"CONDITION"	=>	"#^/hun/solution/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"/hun/solution/index.php",
	),
	array(
		"CONDITION"	=>	"#^/cze/solution/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"/cze/solution/index.php",
	),
	array(
		"CONDITION"	=>	"#^/hrv/about/tv/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"/hrv/about/tv/index.php",
	),
	array(
		"CONDITION"	=>	"#^/eng/products/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"/eng/products/index.php",
	),
	array(
		"CONDITION"	=>	"#^/hrv/solution/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"/hrv/solution/index.php",
	),
	array(
		"CONDITION"	=>	"#^/rus/solution/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"/rus/solution/index.php",
	),
	array(
		"CONDITION"	=>	"#^/bgr/solution/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"/bgr/solution/index.php",
	),
	array(
		"CONDITION"	=>	"#^/eng/about/tv/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"/eng/about/tv/index.php",
	),
	array(
		"CONDITION"	=>	"#^/hun/about/tv/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"/hun/about/tv/index.php",
	),
	array(
		"CONDITION"	=>	"#^/bgr/about/tv/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"/bgr/about/tv/index.php",
	),
	array(
		"CONDITION"	=>	"#^/cze/products/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"/cze/products/index.php",
	),
	array(
		"CONDITION"	=>	"#^/eng/solution/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"/eng/solution/index.php",
	),
	array(
		"CONDITION"	=>	"#^/cze/about/tv/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"/cze/about/tv/index.php",
	),
	array(
		"CONDITION"	=>	"#^/hun/products/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"/hun/products/index.php",
	),
	array(
		"CONDITION"	=>	"#^/rus/about/tv/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"/rus/about/tv/index.php",
	),
	array(
		"CONDITION"	=>	"#^/hrv/products/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"/hrv/products/index.php",
	),
	array(
		"CONDITION"	=>	"#^/about/news/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"/about/news/index.php",
	),
	array(
		"CONDITION"	=>	"#^//solution/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"/hrv/solution/index.php",
	),
	array(
		"CONDITION"	=>	"#^//products/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"/hrv/products/index.php",
	),
	array(
		"CONDITION"	=>	"#^/about/tv/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"/about/tv/index.php",
	),
	array(
		"CONDITION"	=>	"#^/solution/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"/solution/index.php",
	),
	array(
		"CONDITION"	=>	"#^/products/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"/products/index.php",
	),
);

?>